[package]
name = "mipseption"
version = "0.1.0"
edition = "2024"
description = "The worst MIPS interpreter in history"

[profile.release]
codegen-units = 1
lto = "fat"
opt-level = 3
panic = "abort"
strip = "symbols"